### PR TITLE
Make compatible with Meteor 2.3+

### PR DESCRIPTION
**Pull request by StorytellerCZ**

### CODE REVIEW

**Comment by dburles** [comment]
Thanks @StorytellerCZ, I presume it's working okay on 2.3?

**Comment by StorytellerCZ** [comment]
Yes, this allows for the application of `accounts-password` v2, which is from Meteor 2.3 onward.

**Comment by dburles** [comment]
Thanks!

**Comment by dburles** [comment]
@StorytellerCZ Published dburles:two-factor@1.3.1.

**Pull request merged**
